dataset: data/fra-eng/fra.txt
spacy_model: en_trf_bertbaseuncased_lg
val_interval: 5
device: -1

num_epochs: 500
batch_size: 20
flip_prob: null
tune_thresholds: true
use_cross_ent: false

entropy_coef: 0.1

clip_grad_norm: null
clip_grad: null

inference:
  use_sqrt_decay: true
  iterations: 10000
  learning_rate: 1.0
  eps: 0.0001
  region_eps: null

feature_network:
  num_layers: 3
  dropout: 0.5
  learning_rate: 0.0  # not learn
  momentum: 0.0
  weight_decay: 0.0

global_network:
  d_model: 512
  nhead: 8
  dim_feedforward: 2048
  activation: relu
  dropout: 0.1
  num_layers: 2
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0
