model:
  class: spen.SPENModel
  name: spen
num_epochs: 500
batch_size: 20
flip_prob: null
tune_thresholds: true
use_cross_ent: false

pretrained_unary: null
entropy_coef: 0.1

clip_grad_norm: null
clip_grad: null

inference:
  use_sqrt_decay: true
  iterations: 10000
  learning_rate: 1.0
  eps: 0.0001
  region_eps: null

feature_network:
  num_layers: 3
  dropout: 0.5
  learning_rate: 0.0  # not learn
  momentum: 0.0
  weight_decay: 0.0

global_network:
  hidden_size: 16
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0
