model: spen
num_epochs: 500
batch_size: 20
tune_thresholds: true
use_cross_ent: false
optimizer: sgd(lr=0.01, momentum=0.9, weight_decay=0.0)

pretrained_unary: null

clip_grad_norm: null
clip_grad: null

inference:
  use_sqrt_decay: true
  iterations: 10000
  learning_rate: 1.0
  eps: 0.0001
  region_eps: null

feature_network:
  hidden_size: 150
  num_layers: 3
  dropout: 0.5
  freeze: true

global_network:
  hidden_size: 16

entropy_coef: 0.1
