model: unrolled_spen
num_epochs: 500
batch_size: 20
tune_thresholds: true
use_cross_ent: true
optimizer: adam(lr=0.001, betas=(0.9, 0.999), eps=1e-04, weight_decay=0, amsgrad=False)
# optimizer: sgd(lr=0.01, momentum=0.9, weight_decay=0.0)

pretrained_unary: null

clip_grad_norm: null
clip_grad: 1.0

inference:
  optim_type: simple # simple or entropic
  use_sqrt_decay: true
  iterations: 30
  learning_rate: 0.1
  eps: 0.0001
  region_eps: null

feature_network:
  hidden_size: 150
  num_layers: 3
  dropout: 0.5
  freeze: true

global_network:
  hidden_size: 16

entropy_coef: 0.1
